/*
 * TMR_Config.h
 *
 * Created: 10/6/2022 4:44:03 PM
 *  Author: Marwan Yasser
 */ 


#ifndef TMR_CONFIG_H_
#define TMR_CONFIG_H_

#define TMR_TIMER0_PRESCALAR_VALUE	TMR_CLOCK_PRESCALAR_64
#define TMR_TIMER0_OPERATING_MODE	TMR_TIMER0_FAST_PWM_MODE

#define TMR_TIMER1_PRESCALAR_VALUE	TMR_CLOCK_PRESCALAR_8
#define TMR_TIMER1_OPERATING_MODE	TMR_TIMER1_ICR_FAST_PWM_MODE


#endif /* TMR_CONFIG_H_ */